### ISSUE TITLE
Schema re-generation without events from apps

### ISSUE THREAD

**Issue by rymsha** [enonic/app-guillotine#118]
Using https://github.com/enonic/xp/issues/9482 we can check if any part of schema has been modified without employing events.

We need to check lastModified of all schema descriptors periodically and run chshema regeneration is any descriptor has a greater lastModified than we one we observed last. ( We only need to store MAX(lastModified) for comparison)

App guillotine interface, on another hand should show a toast "schema changed" with a lint to refresh GraphiQL UI - quite possible to use custom event for that.

**Comment by sigdestad** [comment]
Looking forward to how / which events we could use instead?
