### ISSUE TITLE
Guillotine - Url Field

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-guillotine#35]
Original questions: Is there any meaningful way to serve image url’s directly from the API? So I don’t have to implement this in the client? Similar to how we provide attachment urls, but maybe with parameters instead?

Proposition:

For all portal URL methods that depend on a specific content or content data, we could add a field on the type. It would avoid an additional call.

```
      attachmentUrl: Field "url" on Attachment, taking as optional parameters:
        "download" boolean
        "type": enum. Either server or absolute.
        "params": object. Custom parameters to append to the url.
      componentUrl: Field "url" on Component, taking as optional parameters:
        "type": enum. Either server or absolute.
        "params": object. Custom parameters to append to the url.
      pageUrl: Field  "url" on Page, taking as optional parameters:
        "type": enum. Either server or absolute.
        "params": object. Custom parameters to append to the url.
```
About the imageURL. The type Image is actually for the content itself (not a subpart). But a field url directly on it seems a bit too generic.

```
      imageUrl: Field "imageUrl" on Image, taking as optional parameters:
        "scale": string
        "quality": number
        "background": string
        "format": format
        "filter": String
        "type": enum. Either server or absolute.
        "params": object. Custom parameters to append to the url.
```

**Comment by sigdestad** [comment]
I like this approach but can we (for this first version) start with only attachmentUrl and imageUrl and url (on content). ImageUrl should perhaps be on top level, and also all media should have mediaUrl -> attachmentUrl for the main attachment?

**Comment by GlennRicaud** [comment]
After discussion with tsi: We will add 3 fields directly at the Content type level:
* pageUrl
* imageUrl (for the content type media:image)
* mediaUrl (for the content types media:*)
  * It will return the attachmentUrl of the first attachment with label 'source'
