### ISSUE TITLE
typo "explose" => "expose"

### ISSUE THREAD

**Issue by hjelmevold** [enonic/app-guillotine#406]
Correct typo "explose" to "expose" (line 21 in endpoints.adoc)

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 670515c8adb9407861a918e0f8a52b96635fcf76
* Document: Endpoints
* Document path: /developer/docs/guillotine/stable/endpoints

**Comment by alansemenov** [comment]
@Anu-MT Thanks, feel free to open a pull request.
