### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by ComLock** [enonic/app-guillotine#49]
Currently guillotine is added to a site and only has access to content from that site.
I've heard this was done deliberatly as a security feature.

We have a setup with where the frontend needs to run a single scored query across multiple sites.

@sigdestad talked about having some configuration in order to allow guillotine to fetch content from other sites.

One solution would be a site config in guillotine. For example a contentSelector with allowType site.
You could for instance also have a contentType selector so that only certain contentTypes would be exposed.

**Comment by mortyeriksen** [comment]
This will be solved using the Guillotine Lib with configuration. It will also include a sample application.
