### ISSUE TITLE
Localize datetime

### ISSUE THREAD

**Issue by ComLock** [enonic/app-guillotine#50]
I would also be cool if one could run localization functions on datetime fields.

For example
moment.locale('nb');
moment().format('L');

But I guess your answer to that would be do it client-side.

**Comment by mortyeriksen** [comment]
You are absolutely right about doing this on the client side :)

Can you confirm that the timezone is correct for the client?

**Comment by GlennRicaud** [comment]
The behaviour is the same as contentLib.get
- DateTimes without timezone are returned as local date time
  - Example: "2018-04-05T00:00"
- DateTimes with timezone are returned with the timezone 
  - Example: "2018-04-04T23:00:00Z"

If you want to localize a DateTime with timezone it is better done client-side as you both said.
I close the issue.
