### ISSUE TITLE
GraphQL query in usage example returns 404

### ISSUE THREAD

**Issue by yngvark** [enonic/app-guillotine#59]
I'm running through doc at the https://github.com/enonic/app-guillotine/blob/master/docs/index.adoc

When doing the GraphQL request against `http://localhost:8080/admin/portal/preview/draft/superhero/_/service/com.enonic.app.superhero/graphql`

The result in the right panel of GraphiQL (http://localhost:8080/admin/tool/com.enonic.app.graphiql/graphiql) is:
```
SyntaxError: Unexpected token < in JSON at position 0
    at fetch.then.response (http://localhost:8080/admin/tool/com.enonic.app.graphiql/graphiql/_/asset/com.enonic.app.graphiql:1521620182/tool/tool.js:7:34)
```

Opening Chrome's console, I see that the error above is a result of  the request to `http://localhost:8080/admin/portal/preview/draft/superhero/_/service/com.enonic.app.superhero/graphql` returns 404.

I believe I have followed the steps in the doc, including adding Guillotine to the Superhero app (which is running), so I don't understand what is wrong. Is the doc missing something?

**Comment by sigdestad** [comment]
Hi.. the problem is the url you are using, it should state "com.enonic.app.guillotine/graphql"

**Comment by yngvark** [comment]
I see. Now it works! I would suggest that the doc should state the correct URL. Thanks anyway.

**Comment by GlennRicaud** [comment]
Yes. It seems it got copied from the lib-guillotine documentation. We will fix.
Thanks for the feedback :+1:
