### ISSUE TITLE
Make it possible to set Access-Control-Allow-Origin in site configuration

### ISSUE THREAD

**Issue by ComLock** [enonic/app-guillotine#62]
It would make it easier when developing a separate frontend not hosted by Enonic. Like for-instance react on express.

**Comment by ComLock** [comment]
https://fetch.spec.whatwg.org/#http-cors-protocol

**Comment by ComLock** [comment]
https://github.com/enonic/starter-headless/blob/master/src/main/resources/controllers/graphql.js#L17-L34

**Comment by rymsha** [comment]
Done with fix https://github.com/enonic/app-guillotine/issues/610
